services:
  ribodb:
    build: .
    container_name: ribodb
    networks:
      - jpfnetwork
    ports:
      - "8008:8008"
    volumes:
      - /Users/flandrs/PKXPLORE/public:/home/genie/app/public
      - /Users/flandrs/PKXPLORE/riboDB/log:/home/genie/app/log
    tty: true
    stdin_open: true

networks:
  jpfnetwork:
    external: true