name = "riboDB"
uuid = "3cf62d8b-d7ac-410c-a0b2-db831a539107"
authors = ["jpflandrs <120022048+jpflandrs@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
StippleDownloads = "291a174b-6542-42e7-9996-fc00d7c03310"